spring:
  data:
    mongodb:
      uri:  mongodb+srv://rastogimanas329:Ys54a4sUZbZpCxhP@cluster0.vl8euvm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: civicinsight
      redis:
        uri: redis-cli -u redis://default:pqi2HBnKCLTTqLtMtrXSYxXGbUUCz6sZ@redis-19844.crce300.ap-south-1-2.ec2.cloud.redislabs.com:19844
  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

groq:
  api:
    key: ${GROQ_API_KEY}
    url: https://api.groq.com/openai/v1/chat/completions

async:
  core-pool-size: 3
  max-pool-size: 10
  queue-capacity: 100

server:
  port: ${PORT:8080}
