spring:
  data:
    mongodb:
      uri: mongodb://rastogimanas329:Ys54a4sUZbZpCxhP@cluster0-shard-00-00.v18euvm.mongodb.net:27017,cluster0-shard-00-01.v18euvm.mongodb.net:27017,cluster0-shard-00-02.v18euvm.mongodb.net:27017/CivicInsight?ssl=true&replicaSet=atlas-v18euvm-shard-0&authSource=admin&retryWrites=true&w=majority
      database: civicinsight
  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

groq:
  api:
    key: ${GROQ_API_KEY}
    url: https://api.groq.com/openai/v1/chat/completions

async:
  core-pool-size: 3
  max-pool-size: 10
  queue-capacity: 100

server:
  port: ${PORT:8080}
